# Dependabot version updates.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      github-actions:
        patterns:
          - '*'
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      go-dependencies:
        patterns:
          - '*'
  - package-ecosystem: 'gomod'
    directory: '/accesstypes'
    schedule:
      interval: 'weekly'
    groups:
      go-dependencies:
        patterns:
          - '*'
  - package-ecosystem: 'gomod'
    directory: '/resource'
    schedule:
      interval: 'weekly'
    groups:
      go-dependencies:
        patterns:
          - '*'
  - package-ecosystem: 'gomod'
    directory: '/pkg'
    schedule:
      interval: 'weekly'
    groups:
      go-dependencies:
        patterns:
          - '*'
  - package-ecosystem: 'gomod'
    directory: '/sns'
    schedule:
      interval: 'weekly'
    groups:
      go-dependencies:
        patterns:
          - '*'
  - package-ecosystem: 'gomod'
    directory: '/lint'
    schedule:
      interval: 'weekly'
    groups:
      go-dependencies:
        patterns:
          - '*'
